language: node_js
node_js:
- 'iojs'
- '0.12'
- '0.10'
- '0.8'
deploy:
  provider: npm
  email: mark@segfawlt.net
  api_key:
    secure: RtrYmA9HH1uQHLGaqTgz+hck9C1jfutEbBk01t43lY6RDgwv3aJ+w98/cL/TvdmQii+Xws1Jn0BxdFNKLpYnKGzuo5GPBgQ8/3PpnuAi0pZlOzno1RZ0E010djWLzJaooxK3/CFf8edjKvoWdkGaSgBCDFG6TFZNFJ7ch08Xr20=
  on:
    tags: true
    repo: markhuge/js-cycle-array
    all_branches: true
    node: 0.12
